Kernel180-BE12/Final-4team-icebang

apps/user-service/build.gradle, apps/user-service/src/main/java/com/gltkorea/icebang/aop/logging/LoggingAspect.java
- AOP logging (aspect)
- Closes #이슈번호
=> AOP logger

.github/workflows/deploy-java.yml, docker/production/docker-compose.yml
=> Release v0.0.1-alpha-SNAPSHOT-20250827.4

apps/user-service/build.gradle, apps/user-service/src/main/resources/application-develop.yml, apps/user-service/src/main/resources/log4j2-develop.yml, apps/user-service/src/main/resources/log4j2-test.yml, docker/local/docker-compose.yml
=> Local 환경 postgre에서 mariadb로 변경

apps/user-service/src/main/java/com/gltkorea/icebang/domain/user/controller/UserController.java, apps/user-service/src/main/java/com/gltkorea/icebang/domain/user/dto/CheckEmailRequest.java, apps/user-service/src/main/java/com/gltkorea/icebang/domain/user/dto/CheckEmailResponse.java, apps/user-service/src/main/java/com/gltkorea/icebang/domain/user/service/UserService.java, apps/user-service/src/main/java/com/gltkorea/icebang/mapper/UserMapper.java
=> Email 중복 확인 api

apps/user-service/src/main/java/com/gltkorea/icebang/domain/auth/controller/AuthController.java, apps/user-service/src/main/java/com/gltkorea/icebang/domain/auth/dto/RegisterDto.java, apps/user-service/src/main/java/com/gltkorea/icebang/domain/auth/service/AuthService.java, apps/user-service/src/main/java/com/gltkorea/icebang/domain/user/service/UserService.java, apps/user-service/src/main/java/com/gltkorea/icebang/mapper/AuthMapper.java, apps/user-service/src/main/resources/mybatis/mapper/AuthMapper.xml
=> User 가입 api

apps/user-service/src/main/java/com/gltkorea/icebang/domain/department/dto/DepartmentCardDo.java, apps/user-service/src/main/java/com/gltkorea/icebang/domain/organization/controller/OrganizationController.java, apps/user-service/src/main/java/com/gltkorea/icebang/domain/organization/dto/OrganizationOptionDto.java, apps/user-service/src/main/java/com/gltkorea/icebang/domain/organization/service/OrganizationService.java, apps/user-service/src/main/java/com/gltkorea/icebang/domain/roles/dto/RoleCardDto.java, apps/user-service/src/main/java/com/gltkorea/icebang/mapper/OrganizationMapper.java, apps/user-service/src/main/resources/application-develop.yml, apps/user-service/src/main/resources/application-test-e2e.yml, apps/user-service/src/main/resources/application-test-unit.yml, apps/user-service/src/main/resources/mybatis/mapper/AuthMapper.xml, apps/user-service/src/main/resources/mybatis/mapper/OrganizationMapper.xml, apps/user-service/src/main/resources/mybatis/mapper/ScheduleMapper.xml, apps/user-service/src/main/resources/sql/00-drop-h2.sql, apps/user-service/src/main/resources/sql/00-drop-maria.sql, apps/user-service/src/main/resources/sql/00-truncate.sql, apps/user-service/src/main/resources/sql/01-insert-internal-users.sql, apps/user-service/src/main/resources/sql/01-schema.sql, apps/user-service/src/main/resources/sql/02-insert-external-users.sql, apps/user-service/src/main/resources/sql/schema.sql, apps/user-service/src/test/java/com/gltkorea/icebang/DatabaseConnectionTest.java
- DTO 네이밍 컨벤션을 준수하도록 리팩토링
- 자바 클래스 단수형 네이밍 사용
- 테이블명을 모두 단수형으로 통일(일관성이 더 중요하다고 판단)
- 추 후 JPA와 같은 ORM을 사용할 때, 테이블 명을 복수형으로 할 경우 매핑이 제대로 되지 않을 수 있음
- 시스템 상에서 이미 단수형으로 테이블이 만들어져 사용되고 있는 경우 백틱 등을 사용해서 진행하는 방식으로
- 외래키 제약 조건 제거
- 성능 향상과 변경에 자유로움의 이점을 가져가기 위해서
- WORKFLOW_RUN, JOB_RUN, TASK_RUN 테이블 추가
- 워크플로우 실행 이력, 작업 실행 이력, 태스크 실행 이력에 대한 데이터를 관리하는 테이블 추가
---
- Closes #이슈번호
---
---
=> 스키마 수정 및 Table 네이밍, DTO 네이밍 컨벤션에 따라 리팩토링

.github/workflows/ci-java.yml, apps/user-service/build.gradle, apps/user-service/src/main/java/com/gltkorea/icebang/config/security/SecurityConfig.java, apps/user-service/src/test/java/com/gltkorea/icebang/config/E2eTestConfiguration.java, apps/user-service/src/test/java/com/gltkorea/icebang/config/RestDocsConfiguration.java, apps/user-service/src/test/java/com/gltkorea/icebang/domain/auth/controller/AuthControllerE2eTest.java, apps/user-service/src/test/java/com/gltkorea/icebang/support/E2eTestSupport.java, apps/user-service/src/test/java/com/gltkorea/icebang/support/E2eTestSupportTest.java
=> User login test 및 rest docs - swagger 설정

apps/user-service/src/main/resources/application.yml
- 패키지명 변경 후 type handler 패키지위치가 제대로 명시되지 않았던 문제
---
- Closes #이슈번호
---
---
=> fix: typeHandler가 등록되지 않는 버그

.github/workflows/deploy-java.yml
- deploy 시 Caddyfile 복사 step 추가
---
- Closes #이슈번호
---
---
=> Ec2에 Caddyfile copy 추가

apps/pre-processing-service/app/api/endpoints/blog.py, apps/pre-processing-service/app/api/endpoints/keywords.py, apps/pre-processing-service/app/api/endpoints/product.py, apps/pre-processing-service/app/api/endpoints/test.py, apps/pre-processing-service/app/model/schemas.py, apps/pre-processing-service/app/service/match_service.py, apps/pre-processing-service/app/service/search_service.py
- 2차 마일스톤에 필요없는 공통 request,response 주석처리
- 사용하지않은 초기설정 URL삭제
---
- Closes #이슈번호
---
---
=>  refactor: 2차 마일스톤을 위한 코드 리팩토링

apps/user-service/build.gradle, apps/user-service/src/main/java/site/icebang/global/filter/LoggingFilter.java, apps/user-service/src/main/resources/application-test-integration.yml, apps/user-service/src/main/resources/log4j2-develop.yml, apps/user-service/src/main/resources/sql/01-schema.sql, docker/local/docker-compose.yml
=> Loki, Grafana 로컬 세팅 및 log 처리

apps/user-service/src/main/resources/application-test-e2e.yml, apps/user-service/src/main/resources/log4j2-test-e2e.yml, apps/user-service/src/test/java/site/icebang/e2e/setup/config/E2eTestConfiguration.java, apps/user-service/src/test/java/site/icebang/e2e/setup/support/E2eTestSupport.java
- Loki test support 추가
- E2e test support에 truncate 추가
- E2e log4j config 분리 
---
- Closes #이슈번호
---
---
=> Loki e2e test support

apps/user-service/build.gradle, apps/user-service/src/main/java/site/icebang/domain/TestController.java, apps/user-service/src/main/java/site/icebang/domain/WorkflowLogInsertExampleController.java, apps/user-service/src/main/java/site/icebang/global/aop/logging/WorkflowLoggingAspect.java, apps/user-service/src/main/java/site/icebang/global/config/security/endpoints/SecurityEndpoints.java, apps/user-service/src/main/java/site/icebang/global/handler/exception/GlobalExceptionHandler.java, apps/user-service/src/main/java/site/icebang/schedule/service/DynamicSchedulerService.java, apps/user-service/src/main/resources/log4j2-develop.yml, apps/user-service/src/main/resources/log4j2-production.yml, apps/user-service/src/main/resources/log4j2-test-e2e.yml
- Log4j2 execution log appender (local)
- example controller 및 logger
- e2e, integration test에서 연동 x
---
- Closes #이슈번호
---
---
=> RDB Log4j2 append (experimental)

apps/user-service/src/main/java/site/icebang/domain/workflow/runner/HttpTaskRunner.java, apps/user-service/src/main/java/site/icebang/domain/workflow/runner/TaskRunner.java, apps/user-service/src/main/java/site/icebang/domain/workflow/service/WorkflowExecutionService.java, apps/user-service/src/main/resources/application.yml, apps/user-service/src/main/resources/sql/03-insert-workflow.sql
- Workflow 관련 insert SQL 변경
- 데이터베이스에 등록된 Workflow(Workflow, Job, Task) 수동 실행 확인
- fast api와 연동해서 테스트 필요
---
- Closes #이슈번호
---
---
=> Spring Quartz, Workflow 실행 확인

.github/workflows/deploy-java.yml, apps/user-service/build.gradle, apps/user-service/src/main/java/site/icebang/global/config/security/SecurityConfig.java, apps/user-service/src/main/resources/application.yml, docker/production/agent-config.yml, docker/production/docker-compose.yml
- actuator 추가
- grafana agent production. docker compose에 추가
- ci 작성
- secret에 관련 env 추가
---
- Closes #이슈번호
---
---
=> Spring actuator - grafana 연동

.github/workflows/deploy-fastapi.yml, apps/pre-processing-service/app/core/logging_config.py, docker/production-fastapi/docker-compose.yml
=> deploy 경로 수정 및 loki config 경로 수정

.github/workflows/deploy-fastapi.yml, apps/pre-processing-service/app/core/logging_config.py, apps/pre-processing-service/poetry.lock
=> onnx 모델 수동 주입 및 logging_config.py 파일 원래대로 변경

docker/production-fastapi/docker-compose.yml
=> fix fastapi docker-compose.yml

.github/workflows/deploy-fastapi.yml, apps/pre-processing-service/app/core/config.py, apps/pre-processing-service/app/core/logging_config.py, apps/pre-processing-service/app/main.py, apps/pre-processing-service/poetry.lock, apps/pre-processing-service/pyproject.toml, docker/production-fastapi/agent-config.yml, docker/production-fastapi/docker-compose.yml
Loki 경로 수정 및 
---
- Closes #이슈번호
---
---
=> Loki 경로 수정 및 grafana-agent 추가 및 환경 변수 추가

apps/pre-processing-service/app/service/crawl_service.py, apps/pre-processing-service/app/service/crawlers/detail_crawler.py
1. 기존에 include_images로 이미지 포함 여부 확인이 false로 되어있었음
2. 그냥 항상 이미지 포함하도록 include_images를 삭제
---
- Closes #이슈번호
---
---
=> 싸다구 크롤링 이미지 포함으로 수정

.github/workflows/ci-java.yml
- GitHub pages에 spring openapi 배포
- 정상 작동 및 버전 태깅 확인 필요
---
- Closes #이슈번호
---
---
=> OpenApi3 (Spring) GitHub pages 배포 (beta)

apps/pre-processing-service/app/api/endpoints/product.py, apps/pre-processing-service/app/model/schemas.py, apps/pre-processing-service/app/service/crawl_service.py, apps/pre-processing-service/app/service/crawlers/search_crawler.py, apps/pre-processing-service/app/service/s3_upload_service.py, apps/pre-processing-service/app/service/search_service.py, apps/pre-processing-service/app/service/similarity_service.py, apps/pre-processing-service/app/utils/s3_upload_util.py, apps/pre-processing-service/poetry.lock, apps/pre-processing-service/pyproject.toml
1. 20개 검색 -> 40개 검색으로 수정
2. 최종 1개 크롤링 -> 최종 10개 이하 크롤링
3. s3 업로드 로직 추가
---
- Closes #이슈번호
---
---
=> 최종 1개 상품 크롤링에서 10개 크롤링으로 수정 및 s3 업로드 로직 추가

.github/workflows/deploy-fastapi.yml, apps/pre-processing-service/app/core/config.py, docker/production-fastapi/docker-compose.yml
Deploy-fastapi 환경 변수 추가 및 config 환경 변수 추가 
---
- Closes #이슈번호
---
---
=> blogger 데이터 및 S3 추가

.github/workflows/deploy-fastapi.yml, apps/pre-processing-service/.dockerignore
=> 오타 수정 및 .onnx ignore 추가

apps/pre-processing-service/app/service/blog/blog_create_service.py
=> Blog_create_blog 원인 파악을 위한 로그

apps/pre-processing-service/app/core/config.py, apps/pre-processing-service/app/service/blog/blog_create_service.py, apps/pre-processing-service/app/utils/llm_extractor.py
- log 로직 변경
- 환경병수 load_dotenv -> setting 사용으로 변경함
---
- Closes #이슈번호
---
---
=> fix: 환경변수 변경및 log 버그 수정

apps/user-service/src/test/java/site/icebang/integration/tests/auth/AuthApiIntegrationTest.java
/v0/auth/check-session
/v0/auth/permissons에 대한 e2eTest 코드 작성
---
- Closes #이슈번호
---
---
=> feat: check-session, permissons api에 대한 테스트 코드 작성

.github/workflows/deploy-fastapi.yml, apps/pre-processing-service/Dockerfile, apps/pre-processing-service/app/utils/keyword_matcher.py
- mecab 환경변수 추가
- mecab 설치 변경
---
- Closes #이슈번호
---
---
=> mecab 설정 변경

apps/pre-processing-service/app/model/schemas.py, apps/pre-processing-service/app/service/crawl_service.py, apps/pre-processing-service/app/service/crawlers/detail_crawler.py, apps/pre-processing-service/app/service/product_selection_service.py, apps/pre-processing-service/app/service/s3_upload_service.py, apps/user-service/src/main/java/site/icebang/domain/workflow/runner/fastapi/body/ProductSelectBodyBuilder.java, apps/user-service/src/main/java/site/icebang/domain/workflow/service/WorkflowExecutionService.java, apps/user-service/src/main/resources/sql/03-insert-workflow.sql
1. 크롤링 및 s3 업로드 비동기로 수정
2. rdb 와 task 실행시 task_run_id 가 mismatch 되던 문제 해결
---
- Closes #이슈번호
---
---
=> 서비스 코드 리팩토링

apps/user-service/src/main/java/site/icebang/domain/user/dto/CheckEmailRequest.java, apps/user-service/src/main/java/site/icebang/domain/user/mapper/UserMapper.java, apps/user-service/src/test/java/site/icebang/integration/tests/user/UserApiIntegrationTest.java
- User controller 아래 모든 api 성공 test
---
- Closes #이슈번호
---
---
=> User 관련 api test 및 api document 작성

apps/user-service/src/main/java/site/icebang/domain/schedule/mapper/ScheduleMapper.java, apps/user-service/src/main/java/site/icebang/domain/workflow/dto/ScheduleCreateDto.java, apps/user-service/src/main/java/site/icebang/domain/workflow/dto/WorkflowCreateDto.java, apps/user-service/src/main/java/site/icebang/domain/workflow/service/WorkflowService.java, apps/user-service/src/main/resources/mybatis/mapper/ScheduleMapper.xml, apps/user-service/src/test/java/site/icebang/e2e/scenario/WorkflowCreateFlowE2eTest.java
schedule 생성 api와 생성할 때 관련된 메서드들 구현입니다.
Quartz에 실시간으로 연동은 구현중이고 잡, 태스크 생성과 연결하기 위해서 1차 pr입니다.
---
- Closes #이슈번호
---
---
=> Schedule 생성 api

apps/pre-processing-service/app/model/schemas.py, apps/pre-processing-service/app/service/blog/blog_create_service.py, apps/pre-processing-service/app/utils/s3_upload_util.py
=> OCR 처리된 텍스트 RAG prompt context에 추가

.github/workflows/deploy-java.yml, apps/user-service/build.gradle, apps/user-service/src/main/resources/log4j2-production.yml, docker/production/docker-compose.yml
- Production jar build 시 reousrce 내 필수 항목만 포함
- application.yml, mapper, log4j2-production.yml
- log4j2-production.yml은 named volume mount
- application-production.yml은 docker image 제외
---
- Closes #이슈번호
---
---
=> Spring 설정 docker image에서 분리 및  Log4j2 자동 감시 추가

apps/pre-processing-service/app/service/blog/blogger_blog_post_adapter.py
- blogger 블로그 생성시 post_url에 response에 넣도록 코드 수정
---
- Closes #이슈번호
---
---
=> fix: blogger post_url 추가

apps/user-service/src/main/resources/mybatis/mapper/TaskRunMapper.xml
=> fix: rag_create 문제 생긴거 수정
